#!/usr/bin/perl

# This script gets all available indexes for a city via aqicn.org
# and enters it into a database for later processing.
# I run it via a cronjob every 15 minutes

use strict;
use warnings;

use DBI;
use WWW::Mechanize;
use HTML::TreeBuilder;
use DateTime;

my $dt          = DateTime->now;
my $created_at  = "$dt->ymd $dt->hms";

my $driver      = "mysql";
my $database    = "lv_pollution";
my $dsn         = "DBI:$driver:database = $database";
my $userid      = "root";
my $password    = "intruder99z";


my $pm25        = 0;
my $pm10        = 0;
my $o3          = 0;
my $no2         = 0;
my $co2         = 0;
my $so2         = 0;
my $temperature = 0;
my $dew         = 0;
my $pressure    = 0;
my $humidity    = 0;
my $wind        = 0;

my $debug       = 0;
my $devel       = 0;

if($debug){
	print "Debug mode on\n";
}

if($devel){
	print "Developer mode on\n";
}

my $m          = WWW::Mechanize->new();
my $url        = 'http://aqicn.org/city/dongguan/';
$m->get($url);
my $content    = $m->content();
my $tree       = HTML::TreeBuilder->new_from_content($content);

if (my $div = $tree->look_down(_tag => "td", id => "cur_pm25")) {
	$pm25 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_pm10")) {
	$pm10 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_o3")) {
	$o3 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_no2")) {
	$no2 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_so2")) {
	$so2 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_co")) {
	$co2 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_t")) {
	$temperature = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_d")) {
	$dew = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_p")) {
	$pressure = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_h")) {
	$humidity = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_w")) {
	$wind = $div->as_text;
}

my $dbh = DBI->connect($dsn, $userid, $password ) or die $DBI::errstr;
my $sth = $dbh->prepare("INSERT INTO pollution (pm25, pm10, o3, no2, so2, co2, temperature, dew, pressure, humidity, wind, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
$sth->execute($pm25, $pm10, $o3, $no2, $so2, $co2, $temperature, $dew, $pressure, $humidity, $wind, $created_at) or die $DBI::errstr;
$sth->finish();

return 0;
