#!/usr/bin/perl

use strict;
use warnings;

use WWW::Mechanize;
use HTML::TableExtract;
use HTML::TreeBuilder;

my $source_url 		= "http://aqicn.org/city/dongguan/";
my $server_endpoint = "http://YOUR_DOMAIN/POST";

my $api_key 	= '123123';
my $source 		= 'aqicn';

my $debug       = 0;
my $devel       = 0;

my $pm25        = 0;
my $pm10        = 0;
my $o3          = 0;
my $no2         = 0;
my $co          = 0;
my $so2         = 0;
my $temperature = 0;
my $dew         = 0;
my $pressure    = 0;
my $humidity    = 0;
my $wind        = 0;

if($debug){
	print "Debug mode on\n";
}

if($devel){
	print "Developer mode on\n";
}

my $m   = WWW::Mechanize->new();
$m->get($source_url);
my $content = $m->content();
my $tree = HTML::TreeBuilder->new_from_content($content);

if (my $div = $tree->look_down(_tag => "td", id => "cur_pm25")) {
	$pm25 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_pm10")) {
	$pm10 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_o3")) {
	$o3 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_no2")) {
	$no2 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_so2")) {
	$so2 = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_co")) {
	$co = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_t")) {
	$temperature = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_d")) {
	$dew = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_p")) {
	$pressure = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_h")) {
	$humidity = $div->as_text;
}

if (my $div = $tree->look_down(_tag => "td", id => "cur_w")) {
	$wind = $div->as_text;
}

my $ua       = LWP::UserAgent->new();
my $response = $ua->post( $server_endpoint, { 
	'source'      => $source,
	'api_key'     => $api_key,
	'pm25'        => $pm25,
	'pm10'        => $pm10,
	'o3'          => $o3,
	'no2'         => $no2,
	'so2'         => $so2,
	'co'          => $co,
	'temperature' => $temperature,
	'dew'         => $dew,
	'pressure'    => $pressure,
	'humidity'    => $humidity,
	'wind'        => $wind
});
$content  = $response->decoded_content();

if ($response->is_success) {
	my $message = $response->decoded_content;
	if($debug || $devel){
		print "Received reply: $message\n";
	}
	exit 0;
} else {
	if($debug || $devel){
		print "HTTP POST error code: ", $response->code, "\n";
		print "HTTP POST error message: ", $response->message, "\n";
	}
	exit 1;
}
