#!/usr/bin/perl

# This program opens a serial connection to a Dyson DC1100 Pro
# and stores the received pm25 and >pm25 values to a database;

use strict;
use warnings;

use Data::Dumper;
use Device::SerialPort;
use DateTime;
use LWP::UserAgent;

my $server_endpoint = "";
my $ua = LWP::UserAgent->new;

my $dt         = DateTime->now;
my $created_at = "$dt->ymd $dt->hms";

my $driver     = "mysql";
my $database   = "lv_pollution";
my $dsn        = "DBI:$driver:database   = $database";
my $userid     = "root";
my $password   = "";
my $host       = "";

my $pm25        = 0;
my $pm10        = 0;
my $temperature = 0;

my $debug       = 0;
my $devel       = 0;

if($debug){
	print "Debug mode on\n";
}

if($devel){
	print "Developer mode on\n";
}

my $port = Device::SerialPort->new("/dev/ttyUSB0");
$port->baudrate(9600);
$port->databits(8);
$port->parity("none");
$port->stopbits(1);

while(1){
	my $input = <STDIN>; # $port->input;
	chomp($input);
	($pm25, $pm10) = split(/,/,$input);

	my $req = HTTP::Request->new(POST => $server_endpoint);
	$req->header('content-type' => 'application/json');
 
	my $post_data = "{'source': 'dyson-home', 'pm25': '$pm25', 'pm10': '$pm10' }";
	$req->content($post_data);
 
	my $resp = $ua->request($req);
	if ($resp->is_success) {
		my $message = $resp->decoded_content;
		print "Received reply: $message\n";
	} else {
		print "HTTP POST error code: ", $resp->code, "\n";
		print "HTTP POST error message: ", $resp->message, "\n";
	}
}

$port->close();
